// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnvfSlYZvyMr_ydIcA92FQmdwkbnffUU',
    appId: '1:386262567854:web:01c4365014ef1d2af4163f',
    messagingSenderId: '386262567854',
    projectId: 'asistab-e0497',
    authDomain: 'asistab-e0497.firebaseapp.com',
    storageBucket: 'asistab-e0497.firebasestorage.app',
    measurementId: 'G-6S7L76MMZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9JfU7g9XVokGiczqxZoc8lZx1Q2sjE4',
    appId: '1:386262567854:android:86401b30c3a1f195f4163f',
    messagingSenderId: '386262567854',
    projectId: 'asistab-e0497',
    storageBucket: 'asistab-e0497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjiVd00u1PACCNtWHvQoamA8mH5RS3SoU',
    appId: '1:386262567854:ios:dcba3d54eacfe8b0f4163f',
    messagingSenderId: '386262567854',
    projectId: 'asistab-e0497',
    storageBucket: 'asistab-e0497.firebasestorage.app',
    iosBundleId: 'com.example.asistab',
  );
}
